"""empty message

Revision ID: c44a12886be7
Revises: f5c92818a7ee
Create Date: 2020-10-07 00:21:23.303870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44a12886be7'
down_revision = 'f5c92818a7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.String(), nullable=False, server_default="avsatn@gmail.com"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###
